- name: Install base prerequisites
  hosts: k3s_cluster
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
    - name: Install packages
      ansible.builtin.apt:
        name:
          - curl
          - ca-certificates
          - openssh-server
        state: present
