apiVersion: v1
kind: Namespace
metadata:
  name: demo-nginx
  labels:
    managed-by: luanvan-platform
    platform/application: demo-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx-web
  namespace: demo-nginx
  labels:
    app.kubernetes.io/name: demo-nginx-web
    app.kubernetes.io/part-of: demo-nginx
    managed-by: luanvan-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo-nginx-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: demo-nginx-web
        app.kubernetes.io/part-of: demo-nginx
    spec:
      containers:
        - name: web
          image: nginx:stable-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: demo-nginx-web
  namespace: demo-nginx
  labels:
    app.kubernetes.io/name: demo-nginx-web
    app.kubernetes.io/part-of: demo-nginx
    managed-by: luanvan-platform
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: demo-nginx-web
  ports:
    - name: http
      port: 80
      targetPort: 80
